- Fixed a crash when 'dataColumn' or 'dateColumn' results in a crash
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 0
at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
at android.database.CursorWrapper.getString(CursorWrapper.java:114)
at com.app.spicit.ResultsView$LoadImagesInBackGround.getImgBasedOnUserFilter(ResultsView.java:1012)
at com.app.spicit.ResultsView$LoadImagesInBackGround.doInBackground(ResultsView.java:951)
at com.app.spicit.ResultsView$LoadImagesInBackGround.doInBackground(ResultsView.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)

- Also fixed an issue when 'placeFound' / 'countryFound' / 'adminFound' has only empty strings.
  The condition 'contains' evaluate to true with empty strings resulting in incorrect pictures added.