Fixed two crashes reproted after staging the Alpha Release
Crash #1 :
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
at com.app.spicit.ResultsView$LoadImagesInBackGround.getImgBasedOnUserFilter(ResultsView.java:1168)

Crash #2:
java.lang.NoSuchMethodError: com.app.spicit.RecyclingImageView.setBackground
at com.app.spicit.RecyclingImageView.setChecked(RecyclingImageView.java:50)